# Generated by Django 5.2.8 on 2025-11-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'bus', 'verbose_name_plural': 'buses'},
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('origen', 'destino')},
        ),
    ]
