# Generated by Django 5.2.8 on 2025-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_bus_options_alter_ruta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='ocupacion_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
