# Generated by Django 5.2.8 on 2025-12-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_bus_ocupacion_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='ocupacion_actual',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='ruta',
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_RUTA', 'En ruta'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_viajes', to='rutas.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_viajes', to='rutas.ruta')),
            ],
            options={
                'ordering': ['fecha', 'hora_salida'],
                'unique_together': {('bus', 'fecha', 'hora_salida')},
            },
        ),
    ]
