# Generated by Django 5.2.8 on 2025-11-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('rutas', '0003_alter_bus_ocupacion_actual'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('asiento', 'bus')},
        ),
    ]
