# Generated by Django 5.2.8 on 2025-11-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0003_alter_bus_ocupacion_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajeros_sugeridos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('ACEPTADA', 'aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('bus_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencia_destino', to='rutas.bus')),
                ('bus_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencia_origen', to='rutas.bus')),
            ],
        ),
    ]
