# Generated by Django 5.2.8 on 2025-11-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(unique=True)),
                ('acuerdo_comision', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_ocupacion', models.PositiveIntegerField()),
                ('ventana_tiempo', models.PositiveIntegerField()),
                ('cooperativa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='cooperativas.cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField()),
                ('ocupacion_actual', models.PositiveIntegerField()),
                ('hora_salida', models.DateTimeField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_buses', to='cooperativas.cooperativa')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_buses', to='cooperativas.ruta')),
            ],
        ),
    ]
