# Generated by Django 5.2.8 on 2025-11-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
