# Generated by Django 5.2.8 on 2025-11-24 08:17

import apps.cooperativas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0002_delete_bus_delete_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncoop',
            name='umbral_ocupacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracioncoop',
            name='ventana_tiempo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cooperativa',
            name='acuerdo_comision',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cooperativa',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, validators=[apps.cooperativas.models.validate_ruc]),
        ),
    ]
