# Generated by Django 5.2.8 on 2025-11-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sugerencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajeros_transferidos', models.PositiveBigIntegerField()),
                ('comision_generada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sugerencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='sugerencias.sugerenciatransferencia')),
            ],
        ),
    ]
